import * as React from "react"; import * as AlertDialogPrimitive from "@radix-ui/react-alert-dialog"; import {cn} from "@/lib/utils"; import {buttonVariants} from "@/components/ui/button";
const AlertDialog=AlertDialogPrimitive.Root,AlertDialogTrigger=AlertDialogPrimitive.Trigger,AlertDialogPortal=AlertDialogPrimitive.Portal;
const AlertDialogOverlay=React.forwardRef<React.ElementRef<typeof AlertDialogPrimitive.Overlay>,React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Overlay>>(({className,...p},r)=><AlertDialogPrimitive.Overlay ref={r} className={cn("fixed inset-0 z-50 bg-black/80",className)} {...p}/>); AlertDialogOverlay.displayName=AlertDialogPrimitive.Overlay.displayName;
const AlertDialogContent=React.forwardRef<React.ElementRef<typeof AlertDialogPrimitive.Content>,React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Content>>(({className,...p},r)=><AlertDialogPortal><AlertDialogOverlay/><AlertDialogPrimitive.Content ref={r} className={cn("fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg",className)} {...p}/></AlertDialogPortal>); AlertDialogContent.displayName=AlertDialogPrimitive.Content.displayName;
const AlertDialogHeader=({className,...p}:React.HTMLAttributes<HTMLDivElement>)=><div className={cn("flex flex-col space-y-2 text-center sm:text-left",className)} {...p}/>;
const AlertDialogFooter=({className,...p}:React.HTMLAttributes<HTMLDivElement>)=><div className={cn("flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2",className)} {...p}/>;
const AlertDialogTitle=React.forwardRef<React.ElementRef<typeof AlertDialogPrimitive.Title>,React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Title>>(({className,...p},r)=><AlertDialogPrimitive.Title ref={r} className={cn("text-lg font-semibold",className)} {...p}/>); AlertDialogTitle.displayName=AlertDialogPrimitive.Title.displayName;
const AlertDialogDescription=React.forwardRef<React.ElementRef<typeof AlertDialogPrimitive.Description>,React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Description>>(({className,...p},r)=><AlertDialogPrimitive.Description ref={r} className={cn("text-sm text-muted-foreground",className)} {...p}/>); AlertDialogDescription.displayName=AlertDialogPrimitive.Description.displayName;
const AlertDialogAction=React.forwardRef<React.ElementRef<typeof AlertDialogPrimitive.Action>,React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Action>>(({className,...p},r)=><AlertDialogPrimitive.Action ref={r} className={cn(buttonVariants(),className)} {...p}/>); AlertDialogAction.displayName=AlertDialogPrimitive.Action.displayName;
const AlertDialogCancel=React.forwardRef<React.ElementRef<typeof AlertDialogPrimitive.Cancel>,React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Cancel>>(({className,...p},r)=><AlertDialogPrimitive.Cancel ref={r} className={cn(buttonVariants({variant:"outline"}),"mt-2 sm:mt-0",className)} {...p}/>); AlertDialogCancel.displayName=AlertDialogPrimitive.Cancel.displayName;
export {AlertDialog,AlertDialogPortal,AlertDialogOverlay,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogFooter,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel};

