import * as React from "react"; import * as SelectPrimitive from "@radix-ui/react-select"; import {Check,ChevronDown,ChevronUp} from "lucide-react"; import {cn} from "@/lib/utils";
const Select=SelectPrimitive.Root, SelectGroup=SelectPrimitive.Group, SelectValue=SelectPrimitive.Value;
const SelectTrigger=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Trigger>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>>(({className,children,...p},r)=><SelectPrimitive.Trigger ref={r} className={cn("flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm",className)} {...p}>{children}<SelectPrimitive.Icon asChild><ChevronDown className="h-4 w-4 opacity-50"/></SelectPrimitive.Icon></SelectPrimitive.Trigger>); SelectTrigger.displayName=SelectPrimitive.Trigger.displayName;
const SelectContent=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Content>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>>(({className,children,position="popper",...p},r)=><SelectPrimitive.Portal><SelectPrimitive.Content ref={r} className={cn("relative z-50 max-h-96 min-w-[8rem] overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md",className)} position={position} {...p}><SelectPrimitive.ScrollUpButton className="flex items-center justify-center py-1"><ChevronUp className="h-4 w-4"/></SelectPrimitive.ScrollUpButton><SelectPrimitive.Viewport className="p-1">{children}</SelectPrimitive.Viewport><SelectPrimitive.ScrollDownButton className="flex items-center justify-center py-1"><ChevronDown className="h-4 w-4"/></SelectPrimitive.ScrollDownButton></SelectPrimitive.Content></SelectPrimitive.Portal>); SelectContent.displayName=SelectPrimitive.Content.displayName;
const SelectLabel=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Label>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Label>>(({className,...p},r)=><SelectPrimitive.Label ref={r} className={cn("py-1.5 pl-8 pr-2 text-sm font-semibold",className)} {...p}/>); SelectLabel.displayName=SelectPrimitive.Label.displayName;
const SelectItem=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Item>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>>(({className,children,...p},r)=><SelectPrimitive.Item ref={r} className={cn("relative flex w-full cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none focus:bg-accent",className)} {...p}><span className="absolute left-2 flex h-3.5 w-3.5 items-center justify-center"><SelectPrimitive.ItemIndicator><Check className="h-4 w-4"/></SelectPrimitive.ItemIndicator></span><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText></SelectPrimitive.Item>); SelectItem.displayName=SelectPrimitive.Item.displayName;
const SelectSeparator=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Separator>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Separator>>(({className,...p},r)=><SelectPrimitive.Separator ref={r} className={cn("-mx-1 my-1 h-px bg-muted",className)} {...p}/>); SelectSeparator.displayName=SelectPrimitive.Separator.displayName;
export {Select,SelectGroup,SelectValue,SelectTrigger,SelectContent,SelectLabel,SelectItem,SelectSeparator};

