/**
 * ACHU-413 (Sesiunea 92) — the customer documents, generated by the app.
 *
 * Roberto asked for this and did not get it: *„ideea era sa le genere din
 * aplicatie"*. He was given three `.docx` templates with highlighted blanks to
 * type by hand (ACHU-411). Archana put it back on the list as high priority,
 * then asked simply: **„Generarea?"**
 *
 * ─── The content is data, not a Word file ────────────────────────────────
 * The wording below is the wording of those three drafts, restructured into
 * blocks so a PDF can be built from it with the customer's details and the
 * business's own settings already filled in — exactly as an invoice or a quote
 * already is.
 *
 * ⛔ **A missing setting is SAID, never left blank.** `missing()` renders a
 * visible marker naming the field and where to set it. An agreement with a
 * silent gap where the insurer should be reads as finished and is not; one that
 * admits the gap cannot be sent by accident. This is the single most important
 * rule in this file.
 *
 * ⚠️ These remain DRAFTS in the legal sense. Generating them from real data
 * does not make them reviewed — `docs/Documente_Clienti/README.md` §"Before you
 * use this document" still applies, and the generated PDF says so on its face.
 */

/** One piece of a document. Deliberately small — the renderer stays dumb. */
export type DocBlock =
  | { kind: 'heading'; text: string }
  | { kind: 'para'; text: string }
  | { kind: 'bullets'; items: string[] }
  | { kind: 'fields'; rows: Array<{ label: string; value: string }> }
  | { kind: 'note'; text: string }
  | { kind: 'ticks'; intro: string; rows: Array<{ label: string; detail: string }> }
  | { kind: 'signature'; left: string; right: string }
  /**
   * 🔴 ACHU-510 (Sesiunea 109) — a signature that HAPPENED, stated on the document.
   *
   * Roberto, having signed in the portal and then downloaded his own copy: *„Deci
   * noi nu semnam? … Și nimeni nu vede semnatura?"* The signature was recorded — in
   * the database, in the audit history, on his screen — and the DOCUMENT still
   * showed two blank lines, exactly as if nothing had happened. A contract that
   * cannot show it was signed is not much use as evidence of having been signed.
   *
   * ⚠️ Distinct from `signature` (the blank ruled lines) on purpose: one is a place
   * to sign, the other is a record that somebody did. Rendering them the same way
   * is what produced the confusion.
   */
  | { kind: 'signed'; lines: string[] };

export interface CustomerDoc {
  /** Right-hand title in the PDF header. */
  title: string;
  /** Used for the download filename. */
  slug: string;
  blocks: DocBlock[];
}

/** Whatever the customer screen holds. All optional — a lead may have nothing. */
export interface DocCustomer {
  customerName?: string | null;
  address?: string | null;
  postcode?: string | null;
  email?: string | null;
  phone?: string | null;
}

/** The business's own settings — the same row the invoice reads. */
export interface DocSettings {
  businessLegalName?: string | null;
  businessAddress?: string | null;
  companyRegistrationNumber?: string | null;
  businessPhone?: string | null;
  insurerName?: string | null;
  insurancePolicyNumber?: string | null;
  insuranceCoverAmount?: string | number | null;
  cancellationNoticeHours?: number | null;
  lateCancellationCharge?: string | number | null;
  noAccessCharge?: string | number | null;
  complaintWindowDays?: number | null;
  paymentTermsDays?: number | null;
}

/**
 * 🔴 The marker for something nobody has filled in yet.
 *
 * ⚠️ It names the SETTING, not just the gap — "[to be completed: Insurer]" sends
 * the reader hunting; this one says where to go. The brackets are deliberately
 * ugly: a document that is not ready should not look ready.
 */
export const missing = (what: string) => `[${what} — set this in Invoice Settings]`;

const text = (v: string | null | undefined, what: string) =>
  (v != null && String(v).trim() !== '' ? String(v).trim() : missing(what));

/**
 * ⚠️ `!= null`, not a truthiness check. A cancellation notice of `0` hours is a
 * real term — "you may cancel at any time" — and `if (!hours)` would replace it
 * with "not set", quietly changing what the customer agreed to.
 */
const money = (v: string | number | null | undefined, what: string) =>
  (v != null && String(v).trim() !== '' ? `£${Number(v).toFixed(2)}` : missing(what));

const count = (v: number | null | undefined, unit: string, what: string) =>
  (v != null ? `${v} ${unit}${v === 1 ? '' : 's'}` : missing(what));

/**
 * 🔴 ACHU-505 (Sesiunea 108) — REMOVED, by Roberto's explicit instruction:
 * *"Porneste… dar scoate textul ala cu draft."*
 *
 * The sentence that used to sit here opened all four documents with "This document
 * is produced from a draft. It has not been reviewed by anyone qualified…". It was
 * written for the OFFICE — an instruction to read the thing before handing it over
 * — and it was correct while these documents only ever reached a customer by
 * somebody choosing to send one.
 *
 * ⚠️ **ACHU-482 is what changed the audience.** Once the customer could open and
 * sign the agreement in the portal, that paragraph appeared directly above the
 * signature box, telling the person about to sign that nobody qualified had checked
 * it. That is why signing was switched off on 09/08.
 *
 * ✅ **Since then the four documents WERE reviewed** — by an external solicitor,
 * against the Consumer Contracts Regulations 2013 and the CMA guidance (ACHU-486…490,
 * 1 HIGH + 5 MEDIUM, all repaired). So the sentence had also stopped being true:
 * it was still telling customers the document was unreviewed after it had been
 * reviewed. Removing it is not hiding a caveat — it is deleting a stale one.
 *
 * ⛔ **What has NOT happened, recorded so nobody infers otherwise from this being
 * gone**: the solicitor asked to see the SIGNING FLOW in the app as well as the
 * document, and that review has not taken place. Roberto was told this in the same
 * exchange and chose to switch signing on — his decision, taken with the fact in
 * front of him. The Consumer/Business split (LOW, deferred by the solicitor's own
 * recommendation) is also still outstanding: `docs/CURRENT_STATE.md` §3.
 */

function customerAddress(c: DocCustomer): string {
  const parts = [c.address, c.postcode].map(p => (p ?? '').trim()).filter(Boolean);
  return parts.length ? parts.join(', ') : missing('the customer address — set it on the customer record');
}

/** Fields shared by the top of every document. */
function partyRows(c: DocCustomer, s: DocSettings, today: string) {
  return [
    { label: 'Company', value: text(s.businessLegalName, 'Legal Business Name') },
    { label: 'Registered address', value: text(s.businessAddress, 'Business Address') },
    { label: 'Company registration number', value: text(s.companyRegistrationNumber, 'Company Registration Number') },
    { label: 'Telephone', value: text(s.businessPhone, 'Business Phone') },
    { label: 'Email', value: 'info@achu.uk' },
    { label: 'Customer', value: text(c.customerName, 'the customer name — set it on the customer record') },
    { label: 'Address where the work will be done', value: customerAddress(c) },
    { label: 'Customer email', value: text(c.email, 'the customer email — set it on the customer record') },
    { label: 'Customer telephone', value: text(c.phone, 'the customer telephone — set it on the customer record') },
    { label: 'Date', value: today },
  ];
}

/** What the app knows about a signature that has already been given. */
export interface RecordedSignature {
  signedName: string;
  /** ISO instant. */
  signedAt: string;
  templateVersion?: string | null;
}

/** The date a signature was given, in the same style the documents use elsewhere. */
function fmtSignedAt(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}

export function serviceAgreement(
  c: DocCustomer,
  s: DocSettings,
  today: string,
  /**
   * ⚠️ Passed ONLY when the signature belongs to the text being rendered. The
   * caller checks that (`LegalDocuments.tsx` already knows, because it decides
   * whether to re-offer the form) — a signature printed on a version the customer
   * never saw would be worse than no signature at all.
   */
  signature?: RecordedSignature | null,
): CustomerDoc {
  const notice = count(s.cancellationNoticeHours, 'hour', 'Cancellation Notice');
  return {
    title: 'SERVICE AGREEMENT',
    slug: 'service-agreement',
    blocks: [
      { kind: 'heading', text: '1. The parties' },
      { kind: 'fields', rows: partyRows(c, s, today) },

      { kind: 'heading', text: '2. What we will do' },
      { kind: 'para', text: 'We will provide the cleaning services agreed with you at the address above. The services, how often we come, how long a visit is expected to take, who supplies the materials and the price are the ones set out in the quote or booking you accepted.' },
      { kind: 'para', text: 'The times we give are estimates made in good faith. If a visit is going to take materially longer or shorter than expected, we will tell you rather than quietly change the price.' },
      { kind: 'para', text: 'We will provide the services with reasonable care and skill.' },

      { kind: 'heading', text: '3. Price, invoices and payment' },
      { kind: 'para', text: `Invoices are due within ${count(s.paymentTermsDays, 'day', 'Payment Terms')} of the invoice date. Each invoice shows its own due date, and that date is the one that applies.` },
      { kind: 'para', text: 'We will tell you before doing any work that would cost more than agreed, and we will not charge for it unless you agree.' },
      { kind: 'para', text: 'If an invoice is not paid by its due date we may pause further visits until it is settled. We will contact you first; we will not simply stop turning up.' },
      { kind: 'para', text: 'If VAT becomes chargeable on these services, invoices will show it separately and the agreed price is treated as including it, so the total you were quoted does not increase.' },

      { kind: 'heading', text: '4. Getting into the property' },
      { kind: 'para', text: 'We can only clean what we can reach. Please make sure we can get in at the agreed time.' },
      { kind: 'bullets', items: [
        'If you will be out, tell us how we get in — and please give us permission to hold a key or entry code first (see "Your permissions" in your account, or ask us if you do not have one), so that permission is recorded rather than assumed.',
        'Please tell us about anything we need to know to work safely: alarms, pets, a room not to enter, an item not to move.',
      ] },
      { kind: 'para', text: `If we arrive at the agreed time and cannot get in, we may charge ${money(s.noAccessCharge, 'No-Access Charge')} towards the cleaner's time and travel. We will always try to reach you first.` },

      { kind: 'heading', text: '5. Changing or cancelling a visit' },
      { kind: 'para', text: `Either of us can move or cancel a visit by giving at least ${notice}' notice.` },
      { kind: 'para', text: `For less notice than that, we may charge ${money(s.lateCancellationCharge, 'Late Cancellation Charge')}, because the cleaner's time has usually already been committed.` },
      { kind: 'para', text: 'If we have to cancel — illness, weather, a vehicle problem — you pay nothing for that visit, and we will offer you the earliest alternative we have.' },
      { kind: 'note', text: 'If you are a consumer and this agreement was made off our business premises (for example: by phone, online, or at your home), you have a 14-day cancellation period under the Consumer Contracts Regulations 2013, and you do not have to give a reason. Full details of this right, how to exercise it, and what happens if we start work during that period, are in the separate Cancellation Rights document — read it before signing.' },

      { kind: 'heading', text: '6. Our people' },
      { kind: 'para', text: 'Our cleaners are our responsibility. We choose them, train them, and pay them; you do not employ them.' },
      { kind: 'para', text: 'Please do not offer our cleaners work directly. If you would like more done, ask us and we will arrange it — this protects both the cleaner and you.' },
      { kind: 'para', text: 'If you would rather a particular cleaner did not return, tell us. You do not have to explain, and it will not affect your service.' },

      { kind: 'heading', text: '7. If something goes wrong' },
      { kind: 'para', text: 'We would much rather hear about a problem than have you live with it.' },
      { kind: 'para', text: `Tell us within ${count(s.complaintWindowDays, 'day', 'Complaint Window')} of the visit and we will return and put it right at no charge, if we can reasonably do so. Tell us about damage or breakage in the same window; we carry public liability insurance and will deal with it properly.` },
      { kind: 'para', text: 'This does not affect your statutory rights, including your right to services performed with reasonable care and skill.' },
      { kind: 'fields', rows: [
        { label: 'Insurer', value: text(s.insurerName, 'Insurer') },
        { label: 'Policy number', value: text(s.insurancePolicyNumber, 'Policy Number') },
        { label: 'Cover', value: money(s.insuranceCoverAmount, 'Cover Amount') },
      ] },
      { kind: 'para', text: 'Some things cannot be made good by cleaning, and we will say so honestly rather than risk them: existing damage, worn or delicate surfaces, and items already broken before we arrived.' },
      { kind: 'para', text: 'Nothing in this agreement limits our liability for death or personal injury caused by our negligence, for fraud, or for anything else that cannot lawfully be limited.' },

      { kind: 'heading', text: '8. Ending this agreement' },
      { kind: 'para', text: 'Either of us may end this agreement by giving one week\'s notice in writing, including by email. You pay for the visits already made, and nothing more.' },
      { kind: 'para', text: 'Either of us may end it immediately if the other seriously breaks it — for example non-payment after a written reminder, or conduct that makes it unsafe for a cleaner to attend.' },

      { kind: 'heading', text: '9. Your personal information' },
      { kind: 'para', text: 'We handle your details as set out in our Privacy Notice, which is a separate document and forms part of this agreement.' },
      { kind: 'para', text: 'In short: we use your details to do this work and to invoice you, we do not sell them, and you have rights over your personal information, including rights of access, correction and, in certain circumstances, erasure — the Privacy Notice explains these fully, including when erasure does not apply (for example, invoices we are legally required to keep).' },

      { kind: 'heading', text: '10. General' },
      { kind: 'bullets', items: [
        'This agreement, together with the quote or booking you accepted, the Privacy Notice, and (where it applies) the Cancellation Rights document, is the whole of what we have agreed. It replaces anything said beforehand.',
        'Any change needs to be agreed in writing by both of us.',
        'If a court finds one clause unenforceable, the rest still stands.',
        'This agreement is governed by the law of England and Wales, and the courts of England and Wales have jurisdiction.',
      ] },

      { kind: 'heading', text: '11. Signatures' },
      { kind: 'para', text: 'By signing, both of us confirm we have read this agreement and the Privacy Notice.' },
      /**
       * ⛔ ACHU-510 — what is printed for ACHU's own side is deliberately NOT a
       * counter-signature. Nobody at ACHU signs anything when a customer signs in
       * the portal, and printing a name there would be asserting an act that did
       * not happen — on the one document where that matters most. What is stated
       * instead is the thing that IS true: ACHU issued this agreement, and it is
       * the party bound by it. Whether ACHU should counter-sign at all is a
       * question for the solicitor, raised with Roberto and NOT decided here.
       */
      ...(signature
        ? [{
          kind: 'signed' as const,
          lines: [
            `Signed by the customer: ${signature.signedName}`,
            `Signed electronically on ${fmtSignedAt(signature.signedAt)}`,
            ...(signature.templateVersion ? [`Version signed: ${signature.templateVersion}`] : []),
            `Issued by ${text(s.businessLegalName, 'Legal Business Name')}, who is bound by this agreement.`,
          ],
        }]
        : [{
          kind: 'signature' as const,
          left: `Signed for ${text(s.businessLegalName, 'Legal Business Name')} — name, position, date`,
          right: 'Signed by the customer — name, date',
        }]),
    ],
  };
}

export function privacyNotice(c: DocCustomer, s: DocSettings, today: string): CustomerDoc {
  return {
    title: 'PRIVACY NOTICE',
    slug: 'privacy-notice',
    blocks: [
      { kind: 'para', text: 'This notice explains what we do with your personal information. It is required by law (UK GDPR, Article 13) and we have to give it to you at the point we collect your details.' },
      { kind: 'fields', rows: [
        { label: 'Who is responsible', value: text(s.businessLegalName, 'Legal Business Name') },
        { label: 'Registered address', value: text(s.businessAddress, 'Business Address') },
        { label: 'Company registration number', value: text(s.companyRegistrationNumber, 'Company Registration Number') },
        { label: 'How to contact us', value: `info@achu.uk · ${text(s.businessPhone, 'Business Phone')}` },
        { label: 'Given to', value: text(c.customerName, 'the customer name — set it on the customer record') },
        { label: 'Date', value: today },
      ] },

      { kind: 'heading', text: 'What we hold, and why' },
      { kind: 'para', text: 'Your name, address, telephone number and email address, the work we have done for you, and the invoices and payments that go with it.' },
      /**
       * ⚠️ The legal basis matters and is deliberately NOT consent. Consent can
       * be withdrawn — if we claimed it as the reason we keep invoices, a
       * withdrawal would appear to oblige us to delete the very records HMRC
       * requires us to keep for six years. The same reasoning is enforced by a
       * test on the public quote form (ACHU-410).
       */
      { kind: 'para', text: 'We hold it because we need it to carry out the work you asked for and to invoice you (performing our contract with you), and because tax law requires us to keep records of what we invoiced (a legal obligation). We do not rely on your consent for any of that — consent can be withdrawn, and we cannot delete records the law requires us to keep.' },
      { kind: 'para', text: 'Some things are genuinely optional and kept separate from this agreement: holding a key or an entry code, entering when you are not at home, photographs and video, and marketing messages. See "Your permissions" in your account, or ask us if you do not have one. You can refuse any of those without affecting your service, and change your mind at any time.' },

      { kind: 'heading', text: 'How long we keep it' },
      /**
       * 🔴 ACHU-545 (Sesiunea 120) — Roberto, asked directly on 12/08/2026: *„datele se
       * pastreaza pana cand clientul decide… Numai ce avem nevoie legal oprim…"*
       *
       * 📜 This paragraph used to end *„for as long as you are a customer, and then only
       * as long as we have a reason to keep it"* — vague in the one direction that
       * matters: it implied deletion happens at some point of the firm's choosing, when
       * in fact **nothing in the code deletes anything on a timetable**. The customer
       * decides, by asking. Corrected rather than reworded quietly, because the old
       * sentence is the one a reader would otherwise quote back.
       *
       * ⚠️ The itemised version of the second sentence — what exactly is erased, deleted,
       * kept or read by hand — is NOT repeated here. It is derived from the erasure policy
       * that runs, and shown in the customer's own account ("How we use your data",
       * `backend/src/lib/privacyNoticeContent.ts`). Copied into this document it would be
       * a second list to keep in step, and this is the copy nobody re-reads.
       */
      { kind: 'para', text: 'Invoices and the records that support them: six years after the end of the tax year they relate to, because HMRC requires it. Everything else: we do not delete it on a timetable — we keep it while you are a customer so we can do your cleans and answer questions about work we have already done, and you decide when that ends by asking us to erase it. After that we keep only what the law requires.' },
      { kind: 'para', text: 'Your account, under "How we use your data", lists exactly what is erased, what is deleted outright, and what we have to keep, item by item.' },

      { kind: 'heading', text: 'Who else sees it' },
      { kind: 'para', text: 'The cleaners who do your work, and the software we use to run the business and store the records. We do not sell your details, and we do not share them for anyone else\'s marketing.' },

      { kind: 'heading', text: 'Your rights' },
      { kind: 'bullets', items: [
        'Ask what we hold about you, and get a copy.',
        'Ask us to correct anything that is wrong.',
        'Ask us to erase it — in certain circumstances. It does not apply to anything we are legally required to keep (for example, invoices HMRC requires us to retain), and we will tell you what that is.',
        'Withdraw any of those optional permissions, at any time.',
        'Complain to the Information Commissioner\'s Office (ico.org.uk) if you think we have got this wrong. We would rather you told us first.',
      ] },
    ],
  };
}

/**
 * ACHU-482, second pass (Sesiunea 100) — a solicitor's review of the live
 * Service Agreement (external audit against the Consumer Contracts
 * Regulations 2013 and current CMA guidance) found HIGH 1: the single
 * sentence in `serviceAgreement()` §5 does not actually implement the
 * 14-day cancellation right — it does not distinguish off-premises/distance
 * contracts properly, does not require an EXPRESS request before starting
 * work inside the period (Regulation 36), and does not carry the mandatory
 * cancellation information at all (MEDIUM 1). This document is that missing
 * information, kept separate on purpose — cramming it into one paragraph of
 * the agreement is exactly what the review flagged as insufficient.
 *
 * ⚠️ Still a DRAFT in the same sense as the other three documents — the
 * review that produced this text is not itself a substitute for a
 * solicitor's sign-off on the FINAL wording actually shipped.
 */
export function cancellationInformation(c: DocCustomer, s: DocSettings, today: string): CustomerDoc {
  return {
    title: 'CANCELLATION RIGHTS',
    slug: 'cancellation-rights',
    blocks: [
      { kind: 'para', text: 'This only applies if you are a consumer (not a business) and this agreement was made away from our business premises — for example over the phone, online, or at your home. If that is not how this agreement was made, this document does not apply to it.' },

      { kind: 'heading', text: 'Your right to cancel' },
      { kind: 'para', text: 'You have the right to cancel this agreement within 14 days without giving any reason. The cancellation period will expire 14 days after the day this agreement is entered into (the day you accept the quote or booking, or sign this agreement, whichever is later).' },
      { kind: 'para', text: 'To exercise the right to cancel, you must inform us of your decision by a clear statement (for example, a letter sent by post, or an email). You may use the model cancellation form below, but you do not have to.' },
      { kind: 'para', text: 'To meet the cancellation deadline, it is enough for you to send your notice of cancellation before the cancellation period has expired.' },

      { kind: 'heading', text: 'If we start work during the cancellation period' },
      { kind: 'para', text: 'We will not begin providing the services during the 14-day cancellation period unless you have expressly asked us to, in writing, using the checkbox provided when you sign this agreement or by separate written request. We keep a record of that request, including when it was made.' },
      { kind: 'para', text: 'If you asked us to begin during the cancellation period and later cancel, you will owe us an amount in proportion to what has been supplied before you told us you were cancelling, compared with the full coverage of this agreement — never more than the price actually agreed.' },
      { kind: 'para', text: 'If the service is FULLY performed during the cancellation period, and you expressly requested this AND acknowledged that you would lose your right to cancel once it was fully performed, your right to cancel is lost once we finish.' },

      { kind: 'heading', text: 'Effect of cancellation' },
      { kind: 'para', text: 'If you cancel this agreement within the cancellation period, we will reimburse all payments received from you, less any amount owed under "If we start work during the cancellation period" above, without undue delay and in any event within 14 days of the day we are informed of your decision to cancel. We will use the same means of payment you used for the original transaction, unless you agree otherwise.' },

      { kind: 'heading', text: 'Model cancellation form' },
      { kind: 'para', text: '(Complete and return this form only if you wish to cancel the agreement.)' },
      { kind: 'fields', rows: [
        { label: 'To', value: `${text(s.businessLegalName, 'Legal Business Name')}, ${text(s.businessAddress, 'Business Address')}, info@achu.uk` },
        { label: 'I/We hereby give notice that I/We cancel', value: 'my/our agreement for the provision of the following service:' },
        { label: 'Ordered on / received on', value: today },
        { label: 'Name of consumer(s)', value: text(c.customerName, 'the customer name — set it on the customer record') },
        { label: 'Address of consumer(s)', value: customerAddress(c) },
        { label: 'Signature (only if this form is submitted on paper)', value: '' },
        { label: 'Date', value: '' },
      ] },
    ],
  };
}

export function consentForm(c: DocCustomer, s: DocSettings, today: string): CustomerDoc {
  return {
    title: 'CONSENT FORM',
    slug: 'consent-form',
    blocks: [
      { kind: 'para', text: 'This form covers only the things that are genuinely optional. You can say no to any of them and it will not affect your service or your price. You can change your mind at any time by telling us.' },
      { kind: 'fields', rows: [
        { label: 'Customer', value: text(c.customerName, 'the customer name — set it on the customer record') },
        { label: 'Address', value: customerAddress(c) },
        { label: 'Date', value: today },
      ] },

      { kind: 'heading', text: '1. Holding a key or an entry code' },
      { kind: 'ticks', intro: 'Please tick one', rows: [
        { label: 'YES', detail: 'You may hold a key or entry code for my property. What you hold: KEY / CODE / BOTH — reference: ................' },
        { label: 'NO', detail: 'I will let the cleaner in at each visit.' },
      ] },

      { kind: 'heading', text: '2. Entering when you are not at home' },
      { kind: 'para', text: 'This is a separate question from the one above: you might give us a code but still want to be in when we clean.' },
      { kind: 'ticks', intro: 'Please tick one', rows: [
        { label: 'YES', detail: 'Cleaners may enter and work when I am not present.' },
        { label: 'NO', detail: 'I will be present for every visit.' },
      ] },

      /**
       * ⚠️ Video is here because Archana asked for it (05/08/2026) and answered
       * the scope question in the same breath: **social media only**. It is
       * deliberately NOT offered for records or training, unlike photographs —
       * asking for consent wider than what was decided is how a form quietly
       * acquires permissions nobody agreed to grant.
       */
      { kind: 'heading', text: '3. Photographs and video' },
      { kind: 'para', text: 'Photographs help in three quite different ways, so they are asked separately. We never photograph or film people, and we never photograph or film anything that identifies where you live.' },
      { kind: 'ticks', intro: 'Please tick any you agree to', rows: [
        { label: '☐', detail: 'Before-and-after photographs kept in our own records, to settle any question about the condition of a room.' },
        { label: '☐', detail: 'Photographs used to train our cleaners, inside the company only.' },
        { label: '☐', detail: 'Photographs used publicly — our website or social media — with no address, no house number, and nothing personal in shot.' },
        { label: '☐', detail: 'Video used on our social media — same limits as the photographs above: no people, no address, nothing that identifies where you live.' },
      ] },
      { kind: 'para', text: 'If you say yes to anything public and change your mind, tell us and we will take it down. We cannot control copies someone else has already made of a public post, and we would rather say so than promise otherwise.' },

      { kind: 'heading', text: '4. Marketing messages' },
      { kind: 'ticks', intro: 'Please tick if you agree', rows: [
        { label: '☐', detail: 'You may send me offers and news about your services. I can unsubscribe at any time.' },
      ] },
      { kind: 'para', text: 'Messages about a booking you already have — a reminder, a change of time, an invoice — are not marketing and will be sent whatever you tick here.' },

      /**
       * 🔴 ACHU-547 (Sesiunea 120) — added the same day as the portal topic, and that is
       * the whole point. This form and `consentTopics.ts` ask the SAME questions of two
       * different people: the portal customer and the one with no account. A question
       * added to one and not the other means two customers of the same firm are asked for
       * different permissions, and only one of them was ever asked about sharing.
       *
       * ⛔ Deliberately does NOT ask about the accountant or the insurer. Those are a
       * legal obligation and a claim respectively — a "no" the firm could not honour. They
       * are named in the Privacy Notice as recipients instead.
       */
      { kind: 'heading', text: '5. Sharing your details outside ACHU' },
      { kind: 'para', text: 'We do not do this today. We are asking now so that your answer is on record if we ever start.' },
      { kind: 'ticks', intro: 'Please tick if you agree', rows: [
        { label: '☐', detail: 'You may pass my name and email to a review website (for example Google or Trustpilot) so that it can invite me to review work you have done for me.' },
      ] },
      { kind: 'para', text: 'Two things this does not cover, because they are not ours to ask: our accountant sees the invoices the law requires us to keep, and our insurer sees what it needs if there is ever a claim about work at your property.' },

      { kind: 'heading', text: 'Signature' },
      { kind: 'signature', left: 'Customer — name, signature, date', right: `Received for ${text(s.businessLegalName, 'Legal Business Name')} — name, date` },
    ],
  };
}

/**
 * Everything Admin can generate for a customer record — includes the Consent
 * Form, a paper-style artifact for a customer with no portal account.
 */
export const CUSTOMER_DOCUMENTS = [
  { key: 'agreement', label: 'Service Agreement', build: serviceAgreement },
  { key: 'cancellation', label: 'Cancellation Rights', build: cancellationInformation },
  { key: 'privacy', label: 'Privacy Notice', build: privacyNotice },
  { key: 'consent', label: 'Consent Form', build: consentForm },
] as const;

/**
 * What the customer PORTAL offers — deliberately excludes the Consent Form.
 *
 * ⚠️ Roberto, Sesiunea 100: the portal already has a live, database-backed
 * consent mechanism (`ConsentSettings.tsx`, ACHU-427) asking the exact same
 * eight questions with real Yes/No buttons, a timestamp and a history (📜 seven
 * until ACHU-547 added the sharing question on 12/08/2026). This
 * static PDF predates it — blank tick-boxes, no submit path, no way for an
 * answer on it to ever reach the database (`source` is hardcoded `'portal'`
 * on the one write path there is, and it isn't this document). Offering both
 * to a signed-in customer risks them believing they answered something here
 * that only "Your permissions" actually records.
 */
export const PORTAL_CUSTOMER_DOCUMENTS = CUSTOMER_DOCUMENTS.filter(d => d.key !== 'consent');

export type CustomerDocumentKey = (typeof CUSTOMER_DOCUMENTS)[number]['key'];

