import * as React from "react"; import * as DialogPrimitive from "@radix-ui/react-dialog"; import {X} from "lucide-react"; import {cn} from "@/lib/utils";
const Dialog=DialogPrimitive.Root,DialogTrigger=DialogPrimitive.Trigger,DialogPortal=DialogPrimitive.Portal,DialogClose=DialogPrimitive.Close;
const DialogOverlay=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Overlay>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Overlay>>(({className,...p},r)=><DialogPrimitive.Overlay ref={r} className={cn("fixed inset-0 z-50 bg-black/80",className)} {...p}/>); DialogOverlay.displayName=DialogPrimitive.Overlay.displayName;
const DialogContent=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Content>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>>(({className,children,...p},r)=><DialogPortal><DialogOverlay/><DialogPrimitive.Content ref={r} className={cn("fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg",className)} {...p}>{children}<DialogPrimitive.Close className="absolute right-4 top-4"><X className="h-4 w-4"/><span className="sr-only">Close</span></DialogPrimitive.Close></DialogPrimitive.Content></DialogPortal>); DialogContent.displayName=DialogPrimitive.Content.displayName;
const DialogHeader=({className,...p}:React.HTMLAttributes<HTMLDivElement>)=><div className={cn("flex flex-col space-y-1.5 text-center sm:text-left",className)} {...p}/>;
const DialogFooter=({className,...p}:React.HTMLAttributes<HTMLDivElement>)=><div className={cn("flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2",className)} {...p}/>;
const DialogTitle=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Title>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>>(({className,...p},r)=><DialogPrimitive.Title ref={r} className={cn("text-lg font-semibold",className)} {...p}/>); DialogTitle.displayName=DialogPrimitive.Title.displayName;
const DialogDescription=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Description>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>>(({className,...p},r)=><DialogPrimitive.Description ref={r} className={cn("text-sm text-muted-foreground",className)} {...p}/>); DialogDescription.displayName=DialogPrimitive.Description.displayName;
export {Dialog,DialogTrigger,DialogPortal,DialogClose,DialogOverlay,DialogContent,DialogHeader,DialogFooter,DialogTitle,DialogDescription};
